/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ca-central-1",
    "aws_cloud_logic_custom": [
        {
            "name": "apie244579f",
            "endpoint": "https://ep7cms09yi.execute-api.ca-central-1.amazonaws.com/staging",
            "region": "ca-central-1"
        }
    ]
};


export default awsmobile;
