/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ca-central-1",
    "aws_cloud_logic_custom": [
        {
            "name": "api58122196",
            "endpoint": "https://9r267nhfbh.execute-api.ca-central-1.amazonaws.com/production",
            "region": "ca-central-1"
        }
    ]
};


export default awsmobile;
